jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: coursier/cache-action@v6
    - continue-on-error: true
      run: sbt -v "+ test"
    strategy:
      matrix:
        include:
        - java: 11
        - java: 21
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
